import { COMPONENT_TYPES } from './XComfortProtocol';

const COMPONENT_MODEL_NAMES: Record<number, string> = {
  [COMPONENT_TYPES.PUSH_BUTTON_1_CHANNEL]: '1-Channel Pushbutton',
  [COMPONENT_TYPES.PUSH_BUTTON_2_CHANNEL]: '2-Channel Pushbutton',
  [COMPONENT_TYPES.PUSH_BUTTON_4_CHANNEL]: '4-Channel Pushbutton',
  [COMPONENT_TYPES.BINARY_INPUT_230V]: 'Binary Input 230V',
  [COMPONENT_TYPES.BINARY_INPUT_BATTERY]: 'Binary Input Battery',
  [COMPONENT_TYPES.MOTION_SENSOR]: 'Motion Detector',
  [COMPONENT_TYPES.TEMPERATURE_SENSOR]: 'Temperature Input CTEU',
  [COMPONENT_TYPES.ANALOG_INPUT]: 'Analog Input CAEE',
  [COMPONENT_TYPES.ANALOG_ACTUATOR]: 'Analog Actuator CAAE',
  [COMPONENT_TYPES.SHADING_ACTUATOR_LEGACY]: 'Shutter Actuator CJAU',
  [COMPONENT_TYPES.REMOTE_CONTROL_2_CHANNEL]: '2-Channel Remote Control',
  [COMPONENT_TYPES.REMOTE_CONTROL_12_CHANNEL]: '12-Channel Remote Control',
  [COMPONENT_TYPES.ROUTER_ACTUATOR]: 'Router Actuator',
  [COMPONENT_TYPES.IMPULSE_INPUT]: 'Impulse Input CIZE',
  [COMPONENT_TYPES.ENERGY_METER]: 'Energy Meter CEMx',
  [COMPONENT_TYPES.SMART_HOME_CONTROLLER]: 'E-Radiator Actuator CHAZ',
  [COMPONENT_TYPES.SMART_HOME_SENSOR]: 'Alarm Pushbutton CHSZ',
  [COMPONENT_TYPES.HEATING_VALVE]: 'Heating Valve CHVZ',
  [COMPONENT_TYPES.MULTI_HEATING_ACTUATOR]: 'Multi Heating Actuator CHAZ',
  [COMPONENT_TYPES.LIGHT_SWITCH_ACTUATOR]: 'Switching Actuator CSAU',
  [COMPONENT_TYPES.DOOR_WINDOW_SENSOR]: 'Door/Window Sensor',
  [COMPONENT_TYPES.DIMMING_ACTUATOR]: 'Dimming Actuator',
  [COMPONENT_TYPES.RC_TOUCH]: 'Room Controller Touch',
  [COMPONENT_TYPES.HEATING_ACTUATOR_1_CHANNEL]: 'Heating Actuator CHAU',
  [COMPONENT_TYPES.BRIDGE]: 'xComfort Bridge',
  [COMPONENT_TYPES.WATER_GUARD]: 'Water Guard',
  [COMPONENT_TYPES.WATER_SENSOR]: 'Water Sensor',
  [COMPONENT_TYPES.SHADING_ACTUATOR]: 'Shutter Actuator CJAU',
  [COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_1_CHANNEL]: '1-Channel Pushbutton Multi Sensor',
  [COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_2_CHANNEL]: '2-Channel Pushbutton Multi Sensor',
  [COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_4_CHANNEL]: '4-Channel Pushbutton Multi Sensor',
  [COMPONENT_TYPES.WEATHER_STATION]: 'Weather Station',
};

const MULTI_CHANNEL_COMPONENTS: Record<number, number> = {
  [COMPONENT_TYPES.PUSH_BUTTON_2_CHANNEL]: 2,
  [COMPONENT_TYPES.PUSH_BUTTON_4_CHANNEL]: 4,
  [COMPONENT_TYPES.REMOTE_CONTROL_2_CHANNEL]: 2,
  [COMPONENT_TYPES.REMOTE_CONTROL_12_CHANNEL]: 12,
  [COMPONENT_TYPES.TEMPERATURE_SENSOR]: 2,
  [COMPONENT_TYPES.ANALOG_INPUT]: 2,
  [COMPONENT_TYPES.IMPULSE_INPUT]: 2,
  [COMPONENT_TYPES.ENERGY_METER]: 4,
  [COMPONENT_TYPES.SMART_HOME_CONTROLLER]: 3,
  [COMPONENT_TYPES.HEATING_ACTUATOR_1_CHANNEL]: 4,
  [COMPONENT_TYPES.MULTI_HEATING_ACTUATOR]: 14,
  [COMPONENT_TYPES.RC_TOUCH]: 8,
  [COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_2_CHANNEL]: 2,
  [COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_4_CHANNEL]: 4,
};

const WALL_SWITCH_COMPONENTS = new Set<number>([
  COMPONENT_TYPES.PUSH_BUTTON_1_CHANNEL,
  COMPONENT_TYPES.PUSH_BUTTON_2_CHANNEL,
  COMPONENT_TYPES.PUSH_BUTTON_4_CHANNEL,
  COMPONENT_TYPES.REMOTE_CONTROL_2_CHANNEL,
  COMPONENT_TYPES.REMOTE_CONTROL_12_CHANNEL,
  COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_1_CHANNEL,
  COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_2_CHANNEL,
  COMPONENT_TYPES.PUSH_BUTTON_MULTI_SENSOR_4_CHANNEL,
  COMPONENT_TYPES.BINARY_INPUT_230V,
  COMPONENT_TYPES.BINARY_INPUT_BATTERY,
]);

export function isSupportedWallSwitchComponentType(compType?: number): boolean {
  return typeof compType === 'number' && WALL_SWITCH_COMPONENTS.has(compType);
}

export function getButtonChannelCount(compType?: number): number {
  if (typeof compType !== 'number') {
    return 1;
  }

  return MULTI_CHANNEL_COMPONENTS[compType] ?? 1;
}

export function getComponentModelName(compType?: number): string | null {
  if (typeof compType !== 'number') {
    return null;
  }

  return COMPONENT_MODEL_NAMES[compType] ?? null;
}
