export const XCOMFORT_CAPABILITIES = {
  PRESET_MODE: 'xcomfort_preset_mode',
  HEATING_DEMAND: 'xcomfort_heating_demand',
  DEVICE_TEMPERATURE: 'xcomfort_device_temperature',
  VALVE_POSITION: 'xcomfort_valve_position',
  SIGNAL_QUALITY: 'xcomfort_signal_quality',
  SIGNAL_STRENGTH: 'xcomfort_signal_strength',
  WIND_SPEED: 'xcomfort_wind_speed',
  RAIN: 'xcomfort_rain',
  PULSES: 'xcomfort_pulses',
  ENERGY_TARIFF: 'xcomfort_energy_tariff',
  ENERGY_TARIFF_LABEL: 'xcomfort_energy_tariff_label',
  ENERGY_CURRENCY: 'xcomfort_energy_currency',
  ENERGY_HISTORY: 'xcomfort_energy_history',
  ENERGY_TODAY: 'xcomfort_energy_today',
  ENERGY_MONTH: 'xcomfort_energy_month',
  ENERGY_COST: 'xcomfort_energy_cost',
  LOAD_MODE: 'xcomfort_load_mode',
  FLOOR_TEMPERATURE: 'xcomfort_floor_temperature',
  FLOOR_MIN_LIMIT: 'xcomfort_floor_min_limit',
  FLOOR_MAX_LIMIT: 'xcomfort_floor_max_limit',
  EXTERNAL_CLIMATE_CONTROL: 'xcomfort_external_climate_control',
} as const;
